//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterApi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("oX6orVxMsRFycNZtr5hGBFVr3")]
        public string OauthConsumerKey {
            get {
                return ((string)(this["OauthConsumerKey"]));
            }
            set {
                this["OauthConsumerKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wU8VUptvBeMUGra0y4b9beP3FiNuwhBtQeUH5VQpdasC7Syz3e")]
        public string OauthConsumerSecret {
            get {
                return ((string)(this["OauthConsumerSecret"]));
            }
            set {
                this["OauthConsumerSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1125129223-L4MrcLzYYZf80ha3BkES4tQUTlHE0oEFOOJSYnq")]
        public string OauthToken {
            get {
                return ((string)(this["OauthToken"]));
            }
            set {
                this["OauthToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cSfUvLOrUBEE3TJHMEpSOhe6Zf4YDuVCYHbXTCgdN3kQI")]
        public string OauthTokenSecret {
            get {
                return ((string)(this["OauthTokenSecret"]));
            }
            set {
                this["OauthTokenSecret"] = value;
            }
        }
    }
}
