//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVisualization.WindowsClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
        public ProjectEntities()
            : base("name=danielmo_project3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<twitter_places> twitter_places { get; set; }
        public DbSet<twitter_profiles> twitter_profiles { get; set; }
        public DbSet<twitter_tweets> twitter_tweets { get; set; }
        public DbSet<weather_condition> weather_condition { get; set; }
        public DbSet<weather_types> weather_types { get; set; }
    }
}
