//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVisualization.WindowsClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class twitter_tweets
    {
        public long id { get; set; }
        public System.DateTime created_at { get; set; }
        public long profile_id { get; set; }
        public string place_id { get; set; }
        public string text { get; set; }
        public string coordinates_lon { get; set; }
        public string coordinates_lat { get; set; }
        public int pindex { get; set; }
        public string language { get; set; }
    }
}
