//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVisualization.WindowsClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather_condition
    {
        public string id { get; set; }
        public System.DateTime date { get; set; }
        public double temperaturegc { get; set; }
        public double windspeedms { get; set; }
        public int windspeedbf { get; set; }
        public int humidity { get; set; }
        public double rainmmu { get; set; }
    }
}
